"""Procedural sock texture rendering."""

from zettaiplot.textures.colors import resolve_color, resolve_palette
from zettaiplot.textures.presets import (
    classic_fishnet,
    lace_sheer_black,
    opaque_white,
    school_stripes,
    sheer_black,
)
from zettaiplot.textures.renderers import render_sock_texture
from zettaiplot.textures.specs import (
    BaseStyle,
    ColorLike,
    ColorPreset,
    FishnetSpec,
    GradientCurve,
    GradientSheerSpec,
    HorizontalStripesSpec,
    LaceTopSpec,
    OpaqueSpec,
    PalettePreset,
    PaletteSpec,
    PolkaDotSpec,
    RGB,
    RGBA,
    RibbedSpec,
    SheerSpec,
    SockTextureKind,
    SockTextureSpec,
)

__all__ = [
    "BaseStyle",
    "ColorLike",
    "ColorPreset",
    "FishnetSpec",
    "GradientCurve",
    "GradientSheerSpec",
    "HorizontalStripesSpec",
    "LaceTopSpec",
    "OpaqueSpec",
    "PalettePreset",
    "PaletteSpec",
    "PolkaDotSpec",
    "RGB",
    "RGBA",
    "RibbedSpec",
    "SheerSpec",
    "SockTextureKind",
    "SockTextureSpec",
    "classic_fishnet",
    "lace_sheer_black",
    "opaque_white",
    "render_sock_texture",
    "resolve_color",
    "resolve_palette",
    "school_stripes",
    "sheer_black",
]
